### ISSUE TITLE
Figure out UI elements and/or framework

### ISSUE THREAD

**Issue by ryanwersal** [FathomDocs/fathom#4]
Considering just using Semantic UI but maybe we want something a bit more...app-y? Thoughts @calebhalvy?

**Comment by calebhalvy** [comment]
From what (little) 've seen, it does look pretty web-y.

**Comment by calebhalvy** [comment]
I think it could work, though.

**Comment by ryanwersal** [comment]
Any preference?

**Comment by calebhalvy** [comment]
No, but I can do some looking.

**Comment by calebhalvy** [comment]
Have you heard of [Photon](http://photonkit.com/), @ryanwersal?

**Comment by ryanwersal** [comment]
Yeah, I think we were tempted to use that originally. I think I'm really up in the air as far as what styling to go with. This seems primarily because there shouldn't be too much UI to speak of (largely just oriented around a command palette concept is what I'm thinking at the moment).

**Comment by calebhalvy** [comment]
That's fair. I guess I like photon a little more than semantic because it feels a little more app oriented and it was made specifically for use with electron.

**Comment by calebhalvy** [comment]
I'm not saying, however, that I couldn't be persuaded another way.

**Comment by ryanwersal** [comment]
I'll move forward with Photon for now. I'll try to avoid making it look exactly like a Mac app but I agree that looking more app-y couldn't hurt.

**Comment by calebhalvy** [comment]
Ok. Sounds good.

**Comment by ryanwersal** [comment]
Figure this taken care of by @calebhalvy actually committing a framework :)
